[package]
name = "cf_preparator"
description = "Tools for generating solutions as single file based on ../codeforces project"
version = "0.1.0"
authors = ["Aleksei Piskunov <piskunov.alesha@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1"
