version: "3.3"

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - redis
    ports:
      - 8080:8080
    dns: 8.8.8.8

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
